version : 2
jobs :
  build:
    docker :
      - image: cimg/base:stable

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: listprocess
          command: |
            sudo systemctl restart docker
            sudo ps -aux | grep docker
            sudo docker build -t test .
            sudo docker run -p 8080:8080 --name test_container test