version : 2
jobs :
  build:
    working_directory: /app
    docker :
      - image: cimg/base:node:latest

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: listprocess
          command: |
            systemctl restart docker
            ps -aux | grep docker
            docker build -t test .
            docker run -p 8080:8080 --name test_container test