version : 2
jobs :
  build:
    docker :
      - image: docker:latest

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: runNodeJsApp
          command: |
            docker build -t test .
            docker run -d -p 8080:8080 --name test_container test
      - run:
          name: networkTest
          command: |
            docker run --network container:test_container appropriate/curl --retry 10 --retry-connrefused http://localhost:8080