version : 2
jobs :
  build:
    docker :
      - image: docker:latest

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: listprocess
          command: |
            docker build -t test .
            docker run -p 8080:8080 --name test_container test